### ISSUE TITLE
Introduce concept of "holding" an object

### ISSUE THREAD

**Issue by MarkOates** [MarkOates/hexagon#28]
Premise is that you "hold" an object from the component navigator (press `H`, `K`?), and then it appears as being "held" in the UI.

From there, you can now use quickkeys to dump text with the held object. For example:

 - dependency
 - listing in a body_dependency_symbols
 - as an ase
 - (other quick-texts that are currently part of the component navigator)

**Comment by MarkOates** [comment]
## Tasks

- [ ] set "holding:" in HUD
- [ ] render "holding:" in HUD
- [ ] clear holding class
- [ ] set "holding" from advanced component navigator
- [ ] set "holding" in system/system
- [ ] add uhnold ui
- [ ] create mechanism for pasting fragments from held class
